layout_spectrum: 0.4820789
typography_spectrum: 0.4982079
color:
  saturation: 0.7959312
  lightness: 0.5928956
  brandStrength: 0.5017921
  brandColors:
    - '#305392'
    - '#171F16'
    - '#919A4B'
    - '#D9D6BE'
    - '#FFFFFF'
  rhythmicContrast: 0.2204778
name: Shawn
